# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ai-learning',
                'doc_host': 'https://spather.github.io',
                'git_url': 'https://github.com/spather/ai-learning',
                'lib_path': 'ai_learning'},
  'syms': {'ai_learning.core': {'ai_learning.core.foo': ('core.html#foo', 'ai_learning/core.py')}}}
